name: Tests
on: [push, pull_request]

jobs:
   tests:
      name: PHP ${{ matrix.php }} Latest
      runs-on: ubuntu-latest
      strategy:
         matrix:
            php: [ '8.1', '8.2', '8.3' ]
            symfony-version: [ '5.4.*', '6.3.*', '6.4.*' ]
            include:
               - php: '8.2'
                 symfony-version: '7.0.*'
         fail-fast: false

      steps:
         -  name: "Add dependencies"
            run: "composer require --no-progress --no-scripts --no-plugins symfony/flex"

         -  name: Checkout code
            uses: actions/checkout@v2

         -  name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
               php-version: ${{ matrix.php }}
               coverage: xdebug
         -  name: Get Composer Cache Directory
            id: composer-cache
            run: echo "::set-output name=dir::$(composer config cache-files-dir)"

         -  name: Cache dependencies
            uses: actions/cache@v3
            with:
               path: ${{ steps.composer-cache.outputs.dir }}
               key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
               restore-keys: ${{ runner.os }}-composer-

         -  name: Setup Composer minimum stability if required
            run: composer config minimum-stability dev
            if: ${{ contains(fromJSON('["6.4.*", "7.0.*"]'), matrix.symfony-version) }}

         -  name: Install symfony version from matrix
            env:
               SYMFONY_VERSION: ${{ matrix.symfony-version }}
            run: |-
               composer require symfony/framework-bundle:$SYMFONY_VERSION --no-update
               composer require symfony/console:$SYMFONY_VERSION --no-update

         -  name: Install Dependencies
            run: composer update --prefer-dist --no-interaction --optimize-autoloader --no-progress

         -  name: Execute tests
            run: composer test
